spring:
  application:
    name: spring-cloud-eureka
server:
   #服务注册中心端口号
   port: 8761
   #关闭保护机制
   enable-self-preservation: false
eureka:
   instance:
       #注册中心id地址
       hostname: localhost
       #服务注册完后，会有一个心跳来持续高收益Spring-server 我还活着，已防止spring-server 剔除任务，
       #将服务实例从服务中排除出去，我们就该操作为服务续约
       #用于定义服务续约任务的调用间隔时间默认30秒
       lease-renewal-interval-in-seconds: 30
       #用于定义服务失效时间 默认90秒
       lease-expiration-duration-in-seconds: 90
   client:
       #是否向服务注册中心注册自己，默认为true
       registerWithEureka: false
       #是否需要去检索寻找服务,因为是注册中心，他的任务是维护服务实例，所以不需要去寻找服务，默认是true
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/