spring:
  application: 
    name: 
      spring-cloud-eureka-high
  # 指定profile=peer1
  profiles: one
server:  
  port: 8000
eureka: 
  instance: 
    hostname: one
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://two:8001/eureka/


    
            
