spring: 
  application: 
    name: 
      spring-cloud-eureka
  # 指定profile=peer2
  profiles: peer2
server: 
  port: 8001
eureka: 
  instance: 
    hostname: peer2

eureka:
  client: 
    serviceUrl: 
      defaultZone: http://peer1:8000/eureka/
    #是否向服务注册中心注册自己，默认为true
    registerWithEureka: false
    #是否需要去检索寻找服务,因为是注册中心，他的任务是维护服务实例，所以不需要去寻找服务，默认是true
    fetchRegistry: false 
            
