spring:
  application: 
    name: 
      spring-cloud-eureka-high
  # 指定profile=peer1
  profiles: peer1
server:  
  port: 8000
eureka: 
  instance: 
    hostname: peer1

eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://peer2:8001/eureka/
    
            
