spring:
  application: 
    name: 
      spring-cloud-eureka-high
  # 指定profile=peer1
  profiles: one
server:  
  port: 8000
eureka: 
  instance: 
    hostname: one
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://admin:admin123@two:8001/eureka/
security:
  basic:
    enabled: true
  user:
    name: admin  # 用户名
    password: admin123   # 用户密码

    
            
