spring: 
  application: 
    name: 
      spring-cloud-eureka-high
  # 指定profile=peer2
  profiles: two
server: 
  port: 8001
eureka: 
  instance: 
    hostname: two
  client: 
    serviceUrl: 
      defaultZone: http://admin:admin123@one:8000/eureka/
    #是否向服务注册中心注册自己，默认为true
    registerWithEureka: false
    #是否需要去检索寻找服务,因为是注册中心，他的任务是维护服务实例，所以不需要去寻找服务，默认是true
    fetchRegistry: false
security:
  basic:
    enabled: true
  user:
    name: admin  # 用户名
    password: admin123   # 用户密码
            
