server:
    port: 8762
spring:
    application:
        #命名服务
        name: service-offer
    cloud: 
      config: 
        server: 
          git: 
            uri: https://github.com/machao0711/config-repo.git
            searchPaths: config-repo
            username: machao0711
            password: 325066abc
eureka:
   instance:
       #注册中心id地址
       hostname: localhost
       #服务注册完后，会有一个心跳来持续高收益Spring-server 我还活着，已防止spring-server 剔除任务，
       #将服务实例从服务中排除出去，我们就该操作为服务续约
       #用于定义服务续约任务的调用间隔时间默认30秒
       lease-renewal-interval-in-seconds: 30
       #用于定义服务失效时间 默认90秒
       lease-expiration-duration-in-seconds: 90
   client:
       serviceUrl:
          defaultZone: http://localhost:8761/eureka/
             
   
            
