eureka:
    client:
        serviceUrl:
            #指定服务注册中心的地址，这里地址为上面创建的服务中心地址
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8762
spring:
    application:
        #命名服务
        name: service-offer
    spring:
      cloud: 
        config: 
          server: 
            git: 
              uri: https://github.com/machao0711/e-fix.git
              search-paths: e-fix/src/main/resources/config
              username: machao0711
              password: 325066abc
              label: master
   
            
